[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[build]
rustflags = ["-Z", "threads=8"]

[workspace]
members = ["renderer", "shader_macros", "shaders", "shaders_common"]

[workspace.dependencies]
glium = "0.36.0"
renderer = { path = "./renderer/" }
glam = "0.29.2"
shaders = { path = "./shaders" }
optick = "1.3.4"

[dependencies]
glium.workspace = true
renderer.workspace = true
shaders.workspace = true
glam.workspace = true
optick.workspace = true

[features]
frustum = ["chunks"]
chunks = []
binary = []
culled = []
greedy = ["binary"]
