[package]
name = "raytracing"
version = "0.1.0"
edition = "2024"

[dependencies]
renderer.workspace = true
glam.workspace = true
common.workspace = true
winit.workspace = true
gl.workspace = true
dashmap.workspace = true
