[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
glam.workspace = true
glium.workspace = true
[target.'cfg(windows)'.dependencies]
optick = { default-features = false, version = "1.3.4" }
