[package]
name = "shader_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.38"
syn = "2.0.96"
shaders_common = { path = "../shaders_common" }
proc-macro2 = "1.0.93"

[lib]
proc-macro = true
