[package]
name = "shader_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full"] }
shaders_common = { path = "../shaders_common" }
proc-macro2 = "1.0.93"

[lib]
proc-macro = true
